# Generated by Django 5.2.6 on 2025-09-15 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bets',
            fields=[
                ('bet_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('match_id', models.IntegerField()),
                ('bet_amount', models.IntegerField()),
                ('win_amount', models.IntegerField()),
                ('bet_team', models.CharField(choices=[('Team1', 'Team1'), ('Team2', 'Team2')], max_length=10)),
                ('bet_status', models.CharField(choices=[('Active', 'Active'), ('Settled', 'Settled')], default='Active')),
                ('bet_time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Deposite',
            fields=[
                ('deposite_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('amount', models.IntegerField()),
                ('payment_SS', models.ImageField(upload_to='deposits/')),
                ('UTR', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Matchess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(unique=True)),
                ('match_name', models.CharField(max_length=100)),
                ('Team1', models.CharField(max_length=50)),
                ('Team2', models.CharField(max_length=50)),
                ('winner_team', models.CharField(blank=True, choices=[('Team1', 'Team1'), ('Team2', 'Team2')], max_length=10, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('match_status', models.CharField(choices=[('UpComing', 'UpComing'), ('Active', 'Active'), ('Completed', 'Completed')], default='UpComing')),
                ('img', models.ImageField(upload_to='images/')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WebsiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('withdraw_id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField()),
                ('amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('balance', models.IntegerField(default=0)),
                ('exp', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.websiteuser')),
            ],
        ),
    ]
